plugins {
    id 'java'
}

group = 'com.springstart'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework:spring-test:7.0.7'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    testImplementation 'org.hamcrest:hamcrest:3.0'
    testImplementation 'com.jayway.jsonpath:json-path:3.0.0'
    implementation 'org.springframework:spring-context:7.0.7'
    implementation 'org.springframework:spring-webmvc:7.0.7'
    implementation 'tools.jackson.core:jackson-databind:3.1.3'

}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
